# Generated by Django 4.2.2 on 2024-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создано'), ('STARTED', 'Начато'), ('COMPLETED', 'Завершено')], default='CREATED', max_length=10),
        ),
    ]
