# Generated by Django 4.2.2 on 2024-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_options_mailing_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Созданный'), ('STARTED', 'Начатый'), ('COMPLETED', 'Завершенный'), ('STOPPED', 'Остановленный')], default='CREATED', max_length=10),
        ),
    ]
